services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ./apps/api
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: formbuilder
      API_PORT: "8080"
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  web:
    build:
      context: ./apps/web
      args:
        NEXT_PUBLIC_API_BASE: http://localhost:8080/api
        NEXT_PUBLIC_WS_BASE: ws://localhost:8080/ws
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  mongo_data:
